name: Apis

on:
  push:
    tags: 
      - '*.*.*'

jobs:
  "daily-tide":
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Docker build action
      uses: docker/setup-buildx-action@v1
      id: buildx
    - name: Push docker image
      uses: docker/build-push-action@v2
      id: docker_build
      with:
        context: ./fetch/src/
        file: ./fetch/src/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.AWS_REPO_URI }}/fetch-tides-api:$RELEASE_VERSION
