name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt-get install -y libssl-dev && rustup target add x86_64-unknown-linux-musl && cargo install cross
    - name: Build
      run: cd fetch && cross build --verbose --target x86_64-unknown-linux-musl
    - name: Publish
      run: cd fetch && cross publish --release --target x86_64-unknown-linux-musl
    - name: List
      run: cd fetch && ls -al ./target/x86_64-unknown-linux-musl/release/
