name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2
    steps:
    - name: Install packages
      run: amazon-linux-extras install -y rust1 && yum install -y tar
    - uses: actions/checkout@v2
    - name: Build
      run: cd fetch && cargo build --verbose
    # - name: Publish
    #   run: cd fetch && cross publish --release --target x86_64-unknown-linux-musl
    # - name: List
    #   run: cd fetch && ls -al ./target/x86_64-unknown-linux-musl/release/
